### ISSUE TITLE
Error in Building OS

### ISSUE THREAD

**Issue by AkshayBhimani** [jakeydoodle123/JOS#7]
I got error in building your OS.
When I tried to build makefile using "make"  command I got error say "**i686-elf-ld command not found**"  .
Can You help me with that or give me some document regarding how to build and run your OS.

**Comment by jacobmealey** [comment]
Hello! 
you have to cross compile binutils for i686-elf because Clang does not have a built in linker. What operating system are you running?

**Comment by harshmange44** [comment]
I'm running it on "Ubuntu 18.04.3 LTS" and facing the same issue. It would be great if you can guide me on 'cross compile binutils for i686-elf'

**Comment by AkshayBhimani** [comment]
I think it will be better if you provide step by step instructions for prerequisites and how to run OS. So that will help us to see where we are missing in requirements. 

I have already installed binutils but still that not worked for me.

**Comment by jacobmealey** [comment]
Okay, I will try to have something up by Friday evening. 
In general the tools you will need are:
- [i686 binutils](https://github.com/lordmilko/i686-elf-tools)
- Clang
- Qemu

once these three are installed you should be able to run `make run` and it should compile and open in qemu. 

P.S. 
I am glad to see people are taking an interest in JOS, I haven't done any serious development on this in quite a few years. It was a first stab at building an OS for me. I hope I am able to help you guys out as much as possible.

**Comment by jacobmealey** [comment]
Also, if you don't mind me asking, how did you two come across this project?

**Comment by harsh760** [comment]
Hi @jacobmealey ,
We(I , @AkshayBhimani , @dc-exe and @harshmange44 ) are junior year university students and as for our project we were supposed to contribute in any open source OS.
It would be great opportunity to collaborate.
Thank you for responding.

**Comment by jacobmealey** [comment]
Oh, wonderful! 
depending on how much you have looked around the project you will see that I have not done too much work on this project in quite a long time. If you go to the [to-do list](https://github.com/jacobmealey/JOS/blob/master/todo.md) you will see that there are a few things from a long time ago. I am also open to accepting most pull requests/redesigns!

I built this when I was 17 so it's pretty poorly designed, so really feel free to restructure anything! 

I'll make up a little contribution guide as well as a getting started and will try to get it up by tomorrow evening.

**Comment by harsh760** [comment]
> In general the tools you will need are:
> 
>     * [i686 binutils](https://github.com/lordmilko/i686-elf-tools)
> 
>     * Clang
> 
>     * Qemu
> 
> 
> once these three are installed you should be able to run `make run` and it should compile and open in qemu.

Thanks.
This worked for me.
I don't know why but my binutils packages were not installed properly and were causing issues.

**Comment by jacobmealey** [comment]
ahh, makes sense. binutils (and GCC) are very annoying to set up. The reason I set it up with Clang as the compiler is because it has really good built-in cross compilers. I will close this issue now.
