### ISSUE TITLE
facing errors in make command after making changes

### ISSUE THREAD

**Issue by PrashamMody** [jakeydoodle123/JOS#8]
Even if I try to make a small change in any file and try to build all files again using the 'make' command, I am facing the following error:

i686-elf-ld -T linker.ld -o JOS.bin obj/boot.o obj/kernel.o obj/vga.o obj/keyboard.o obj/common.o obj/shell.o obj/ata.o obj/fat.o obj/heap.o obj/parse.o obj/file_parse.o obj/josl.o obj/calc.o 
make: i686-elf-ld: Command not found
make: *** [makefile:9: JOS.bin] Error 127

I do not face this errors if I run the project as it is at first but on making small changes I face this error. Also, if I remove the changes and try to run the project again as I downloaded it, I face the above error.

Do you have any suggestions for that?

**Comment by jacobmealey** [comment]
Hello, 

The issue is that you do not have i686 Binutils installed. please refer to [issue 7](https://github.com/jacobmealey/JOS/issues/7).
If you are still facing issues let me know.

-- Jacob

**Comment by viju3037** [comment]
I installed i686 Binutils but still i686-elf-ld: Command not found error pop up again

**Comment by jacobmealey** [comment]
Hm... very interesting, where are you installing it to? 
is it being included into your PATH?

**Comment by viju3037** [comment]
ok now it's working
