### ISSUE TITLE
Error in adding other c programs

### ISSUE THREAD

**Issue by AkshayBhimani** [jakeydoodle123/JOS#9]
I wants to add some functionalities in OS. So, I have created C file and its working with gcc compiler but when I run it with clang (by adding it to makefile and run) it throws error 
**undefined reference to malloc , 
undefined reference to fopen** 
and some other errors like this though I have included **stldlib.h** .

Also, can you provide some instruction to add c files to work properly in this OS

**Comment by jacobmealey** [comment]
hello, 
sorry for the late reply! The standard library is not ported to JOS, there is a version of malloc in heap.c, this project was built from the ground up, so any of those features must be built-in. 

also, have you added the c file to the makefile?

**Comment by AkshayBhimani** [comment]
Yes, I have added c file to makefile. But, what if I wants to use standard libraries like `stdlib.h , stdio.h , math.h . `
Can I use it or not?

If yes, Can you provide some flags or setting required for that.

**Comment by jacobmealey** [comment]
you cannot use the standard library
